from yacs.config import CfgNode as CN


_C = CN()

# PATHS
_C.PATHS = CN()
_C.PATHS.VID_DIR = ""
_C.PATHS.OPENFACE_DIR = ""
_C.PATHS.TED_DIR = ""
_C.PATHS.VIS_PATH = ""

# TED
_C.TED = CN()
_C.TED.WINDOW = 10

# JSON FILES
_C.JSON = CN()
_C.JSON.TOUCH_TS = ""

# DATASET
_C.DATASET = CN()
_C.DATASET.N_CLASS = 2
_C.DATASET.N_CHAN = 3
_C.DATASET.IMG_SIZE = 224
_C.DATASET.NUM_WORKERS = 4
_C.DATASET.CAMERA_VIEW = "face"
_C.DATASET.NUM_FRAMES = 50
_C.DATASET.TED_SPLIT = [100, 20]
_C.DATASET.AUTH = False
_C.DATASET.TRAIN_HIGH = True
_C.DATASET.VAL_HIGH = False
_C.DATASET.SINGLE_AUG = False

# MODEL
_C.MODEL = CN()
_C.MODEL.FEAT = 20
_C.MODEL.ENC_DIM = 512
_C.MODEL.DROPOUT = 0.2
_C.MODEL.TEMP = 0.1

# SPLIT
_C.SPLIT = CN()
_C.SPLIT.SUBJECT = "P0009"
_C.SPLIT.VAL_SPLIT = "sess"
_C.SPLIT.SPLIT_VALUE = "S3"
_C.SPLIT.COUNT = [5000, 20]
_C.SPLIT.IMPOSTER = "P0004"

# TRAINING
_C.TRAINING = CN()
_C.TRAINING.BATCH = 32
_C.TRAINING.LR = 1e-4
_C.TRAINING.WT_DECAY= 1e-4
_C.TRAINING.ITER = 1
_C.TRAINING.SAMPLER = False
_C.TRAINING.LMBD = 1.

# FLOW
_C.FLOW = CN()
_C.FLOW.N_FLOW = 8
_C.FLOW.N_BLOCK = 1
_C.FLOW.N_CHAN = 2
_C.FLOW.MLP_DIM = 23
_C.FLOW.N_BITS = 5
_C.FLOW.TEMP = 0.7
_C.FLOW.N_SAMPLE = 20

# LR
_C.LR = CN()
_C.LR.WARM = False
_C.LR.WARM_ITER = 30
_C.LR.WARMUP_FROM = 0.01
_C.LR.ADJUST = False
_C.LR.DECAY_RATE = 0.1
_C.LR.MIN_LR = 0.01
_C.LR.T_MAX = 100

# TRANSFORMER:
_C.TRANSFORMER = CN()
_C.TRANSFORMER.DIM_IN = 16
_C.TRANSFORMER.DIM_OUT = 64
_C.TRANSFORMER.DEPTH = 1
_C.TRANSFORMER.HEADS=1
_C.TRANSFORMER.DIM_HEAD=64
_C.TRANSFORMER.MLP_DIM=64
_C.TRANSFORMER.DROPOUT=0.2
_C.TRANSFORMER.POOL="cls"
_C.TRANSFORMER.PATCH_SIZE=8

# COMMENTS
_C.COMMENTS = ""

def get_cfg_defaults():
  """Get a yacs CfgNode object with default values for my_project."""
  # Return a clone so that the defaults will not be altered
  # This is for the "local variable" use pattern
  return _C.clone()